# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-json
    - id: check-ast
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
      args: [--unsafe]
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    name: Run black formatter
    language_version: python3.9
- repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.3
  hooks:
  - id: autoflake
    args: ['--in-place', '--remove-all-unused-imports']
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    name: Run flake8 linter
    additional_dependencies: ["flake8-bugbear==20.11.1", "pep8-naming==0.11.1"]
- repo: https://github.com/timothycrosley/isort
  rev: 5.11.5
  hooks:
  - id: isort
    additional_dependencies: [toml]
    name: Sort imports using isort
- repo: https://github.com/asottile/pyupgrade
  rev: v2.25.0
  hooks:
  - id: pyupgrade
    name: Check for code that can use new Python features
    args: [--py39-plus]
- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  rev: v1.0.4
  hooks:
  - id: python-bandit-vulnerability-check
    args: [-l, --recursive, -x, "tests,docs/source/_static/dbt_project/tests"]
    name: Check for vulnerabilities in code with bandit
    files: .py$
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.1.3
  hooks:
  - id: python-safety-dependencies-check
    name: Check for vulnerable dependencies
- repo: https://github.com/detailyang/pre-commit-shell
  rev: 1.0.5
  hooks:
  - id: shell-lint
